In [125]:
import pandas as pd
import numpy as np
import math as m
import random as rd
from scipy import stats
from sklearn.preprocessing import LabelEncoder

def find_missing_values():
    missing_vals = []
    num_cols = len(data.columns)
    for i in range(num_cols):
        if data.isnull().sum()[i] != 0:
            missing_vals.append(data.columns[i])
    return missing_vals

def input_missing_values(mis_vals):
    if mis_vals != []:
        for col in mis_vals:
            data[col].mean()

def find_incorrect_values():
    incorrect_values = []
    for col in data.columns:
        for val in data[col]:
            if val == "Unknown":
                incorrect_values.append(col)
                break
    return incorrect_values

def change_incorrect_values(inc_vals):
    if inc_vals != []:
        for val in inc_vals:
            change_unknown(val)

def change_unknown(col):
    pcts_dict, unknown_num = calc_pcts(col)
    unknown_people = {}
    for name,pct in pcts_dict.items():
        unknown_people[name] = round(unknown_num*pct)
    new_col = []
    for val in data[col]:
        if val == "Unknown":
            ran_name = rd.randint(1, len(unknown_people))
            name = list(unknown_people.keys())[ran_name-1]
            while True:
                if unknown_people[name] != 0:
                    unknown_people[name] -= 1
                    break
                else:
                    ran_name = rd.randint(1, len(unknown_people))
                    name = list(unknown_people.keys())[ran_name-1]
            new_col.append(name)
        else:
            new_col.append(val)
    data[col] = new_col
            
def calc_pcts(col):
    slices = []
    labels = list(set(data[col]))
    for i in range(len(labels)):
        if labels[i] == "Unknown":
            labels.pop(i)
            break
    for sector in labels:
        slices.append(list(data[col]).count(sector))
    pcts_list = []
    sum = np.sum(slices)
    for val in slices:
        pcts_list.append(val/sum) 
    pcts_dict = {}
    for i in range(len(labels)):
        pcts_dict[labels[i]] = pcts_list[i]
    unknown_num = list(data[col]).count("Unknown")
    return (pcts_dict, unknown_num)

def step1():
    input_missing_values(find_missing_values())
    change_incorrect_values(find_incorrect_values())

def str_to_int(col, str_vals, int_vals):
    new_col = []
    for val in data[col]:
        for i in range(len(str_vals)):
            if str_vals[i] == val:
                new_col.append(int_vals[i])
    data[col] = new_col
    
def sti_Attr_Flag():
    name = "Attrition_Flag"
    str_vals = ['Attrited Customer', 'Existing Customer']
    int_vals = [ 1, 0 ]
    return (name, str_vals, int_vals)

def sti_Gender():
    name = "Gender"
    str_vals = ['M', 'F']
    int_vals = [ 1, 0 ]
    return (name, str_vals, int_vals)

def sti_Mar_Stat():
    name = "Marital_Status"
    str_vals = ['Single', 'Divorced', 'Married']
    int_vals = [ 0, 1, 2 ]
    return (name, str_vals, int_vals)

def sti_Card_Cat():
    name = "Card_Category"
    str_vals = ['Blue', 'Silver', 'Gold', 'Platinum']
    int_vals = [ 0, 1, 2, 3 ]
    return (name, str_vals, int_vals)

def sti_Educ_Lvl():
    name = "Education_Level"
    str_vals = ['Uneducated', 'High School', 'College', 'Graduate', 'Post-Graduate', 'Doctorate']
    int_vals = [ 0, 1, 2, 3, 4, 5 ]
    return (name, str_vals, int_vals)

def sti_Income_Cat():
    name = "Income_Category"
    str_vals = ['Less than $40K', '$40K - $60K', '$60K - $80K', '$80K - $120K', '$120K +']
    int_vals = [ 20000, 50000, 70000, 100000, 140000 ]
    return (name, str_vals, int_vals)

def step3():
    #n - name, s - str_vals, i - int_vals
    n,s,i = sti_Attr_Flag()
    str_to_int(n,s,i)
    n,s,i = sti_Gender()
    str_to_int(n,s,i)
    n,s,i = sti_Mar_Stat()
    str_to_int(n,s,i)
    n,s,i = sti_Card_Cat()
    str_to_int(n,s,i)
    n,s,i = sti_Educ_Lvl()
    str_to_int(n,s,i)
    n,s,i = sti_Income_Cat()
    str_to_int(n,s,i)

data = pd.read_csv("BankChurners.csv")
    
print("\nOLD DATA")
print("====================================================")
print(data)
print("====================================================")
step1()
step3()
data = data[(np.abs(stats.zscore(data)) < 3).all(axis=1)]    #step2:  discovering outliers
print("\n\nNEW DATA")
print("====================================================")
print(data)
print("====================================================")

OLD DATA
====================================================
       CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0      768805383  Existing Customer            45      M                3
1      818770008  Existing Customer            49      F                5
2      713982108  Existing Customer            51      M                3
3      769911858  Existing Customer            40      F                4
4      709106358  Existing Customer            40      M                3
...          ...                ...           ...    ...              ...
10122  772366833  Existing Customer            50      M                2
10123  710638233  Attrited Customer            41      M                2
10124  716506083  Attrited Customer            44      F                1
10125  717406983  Attrited Customer            30      M                2
10126  714337233  Attrited Customer            43      F                2

      Education_Level Marital_Status Income_Category Card_Category  \
0         High School        Married     $60K - $80K          Blue
1            Graduate         Single  Less than $40K          Blue
2            Graduate        Married    $80K - $120K          Blue
3         High School        Unknown  Less than $40K          Blue
4          Uneducated        Married     $60K - $80K          Blue
...               ...            ...             ...           ...
10122        Graduate         Single     $40K - $60K          Blue
10123         Unknown       Divorced     $40K - $60K          Blue
10124     High School        Married  Less than $40K          Blue
10125        Graduate        Unknown     $40K - $60K          Blue
10126        Graduate        Married  Less than $40K        Silver

       Months_on_book  ...  Credit_Limit  Total_Revolving_Bal  \
0                  39  ...       12691.0                  777
1                  44  ...        8256.0                  864
2                  36  ...        3418.0                    0
3                  34  ...        3313.0                 2517
4                  21  ...        4716.0                    0
...               ...  ...           ...                  ...
10122              40  ...        4003.0                 1851
10123              25  ...        4277.0                 2186
10124              36  ...        5409.0                    0
10125              36  ...        5281.0                    0
10126              25  ...       10388.0                 1961

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0              11914.0                 1.335             1144              42
1               7392.0                 1.541             1291              33
2               3418.0                 2.594             1887              20
3                796.0                 1.405             1171              20
4               4716.0                 2.175              816              28
...                ...                   ...              ...             ...
10122           2152.0                 0.703            15476             117
10123           2091.0                 0.804             8764              69
10124           5409.0                 0.819            10291              60
10125           5281.0                 0.535             8395              62
10126           8427.0                 0.703            10294              61

       Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  \
0                    1.625                  0.061
1                    3.714                  0.105
2                    2.333                  0.000
3                    2.333                  0.760
4                    2.500                  0.000
...                    ...                    ...
10122                0.857                  0.462
10123                0.683                  0.511
10124                0.818                  0.000
10125                0.722                  0.000
10126                0.649                  0.189

       Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  \
0                                               0.000093
1                                               0.000057
2                                               0.000021
3                                               0.000134
4                                               0.000022
...                                                  ...
10122                                           0.000191
10123                                           0.995270
10124                                           0.997880
10125                                           0.996710
10126                                           0.996620

       Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0                                               0.999910
1                                               0.999940
2                                               0.999980
3                                               0.999870
4                                               0.999980
...                                                  ...
10122                                           0.999810
10123                                           0.004729
10124                                           0.002118
10125                                           0.003294
10126                                           0.003377

[10127 rows x 23 columns]
====================================================


NEW DATA
====================================================
       CLIENTNUM  Attrition_Flag  Customer_Age  Gender  Dependent_count  \
5      713061558               0            44       1                2
10     708790833               0            42       1                5
14     712396908               0            57       0                2
19     709327383               0            45       0                2
20     806165208               0            47       1                1
...          ...             ...           ...     ...              ...
10119  716893683               1            55       0                3
10123  710638233               1            41       1                2
10124  716506083               1            44       0                1
10125  717406983               1            30       1                2
10126  714337233               1            43       0                2

       Education_Level  Marital_Status  Income_Category  Card_Category  \
5                    3               2            50000              0
10                   0               2           140000              0
14                   3               2            20000              0
19                   3               2           100000              0
20                   5               1            70000              0
...                ...             ...              ...            ...
10119                0               0            20000              0
10123                3               1            50000              0
10124                1               2            20000              0
10125                3               2            50000              0
10126                3               2            20000              1

       Months_on_book  ...  Credit_Limit  Total_Revolving_Bal  \
5                  36  ...        4010.0                 1247
10                 31  ...        6748.0                 1467
14                 48  ...        2436.0                  680
19                 37  ...       14470.0                 1157
20                 42  ...       20979.0                 1800
...               ...  ...           ...                  ...
10119              47  ...       14657.0                 2517
10123              25  ...        4277.0                 2186
10124              36  ...        5409.0                    0
10125              36  ...        5281.0                    0
10126              25  ...       10388.0                 1961

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
5               2763.0                 1.376             1088              24
10              5281.0                 0.831             1201              42
14              1756.0                 1.190             1570              29
19             13313.0                 0.966             1207              21
20             19179.0                 0.906             1178              27
...                ...                   ...              ...             ...
10119          12140.0                 0.166             6009              53
10123           2091.0                 0.804             8764              69
10124           5409.0                 0.819            10291              60
10125           5281.0                 0.535             8395              62
10126           8427.0                 0.703            10294              61

       Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  \
5                    0.846                  0.311
10                   0.680                  0.217
14                   0.611                  0.279
19                   0.909                  0.080
20                   0.929                  0.086
...                    ...                    ...
10119                0.514                  0.172
10123                0.683                  0.511
10124                0.818                  0.000
10125                0.722                  0.000
10126                0.649                  0.189

       Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  \
5                                               0.000055
10                                              0.000191
14                                              0.000114
19                                              0.000055
20                                              0.000057
...                                                  ...
10119                                           0.996910
10123                                           0.995270
10124                                           0.997880
10125                                           0.996710
10126                                           0.996620

       Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
5                                               0.999940
10                                              0.999810
14                                              0.999890
19                                              0.999940
20                                              0.999940
...                                                  ...
10119                                           0.003088
10123                                           0.004729
10124                                           0.002118
10125                                           0.003294
10126                                           0.003377

[9202 rows x 23 columns]
====================================================